In [1]:
import numpy as np

# Creating a vector using a list
vector_1 = [1, 2, 3]

# Creating a vector using a NumPy array
vector_2 = np.array([4, 5, 6])

print("Vector 1:", vector_1)
print("Vector 2:", vector_2)

Vector 1: [1, 2, 3]
Vector 2: [4 5 6]


In [2]:
import numpy as np

vector_1 = np.array([1, 2, 3])
vector_2 = np.array([4, 5, 6])

# Vector addition
vector_sum = vector_1 + vector_2
print("Vector sum:", vector_sum)

# Scalar multiplication
scalar = 2
vector_scaled = scalar * vector_1
print("Scaled vector:", vector_scaled)

# Dot product
dot_product = np.dot(vector_1, vector_2)
print("Dot product:", dot_product)

Vector sum: [5 7 9]
Scaled vector: [2 4 6]
Dot product: 32


In [3]:
import numpy as np

# Creating a matrix
matrix_1 = np.array([[1, 2], [3, 4], [5, 6]])
print("Matrix 1:\n", matrix_1)

# Accessing matrix elements
print("\nElement at (1, 1):", matrix_1[0, 1])

# Matrix shape
print("\nMatrix shape:", matrix_1.shape)

Matrix 1:
 [[1 2]
 [3 4]
 [5 6]]

Element at (1, 1): 2

Matrix shape: (3, 2)


In [4]:
import numpy as np

matrix_1 = np.array([[1, 2], [3, 4]])
matrix_2 = np.array([[5, 6], [7, 8]])

# Matrix addition
matrix_sum = matrix_1 + matrix_2
print("Matrix sum:\n", matrix_sum)

# Scalar multiplication
scalar = 2
matrix_scaled = scalar * matrix_1
print("\nScaled matrix:\n", matrix_scaled)

# Matrix multiplication
matrix_product = np.matmul(matrix_1, matrix_2)
print("\nMatrix product:\n", matrix_product)

Matrix sum:
 [[ 6  8]
 [10 12]]

Scaled matrix:
 [[2 4]
 [6 8]]

Matrix product:
 [[19 22]
 [43 50]]


In [5]:
import numpy as np

# Coefficients of the linear equations
A = np.array([[2, 1], [1, 3]])
b = np.array([5, 11])

# Solving the system of linear equations
x = np.linalg.solve(A, b)

print("Solution:")
print(x)

Solution:
[0.8 3.4]


In [6]:
import numpy as np

# Matrix
A = np.array([[3, 1], [1, 3]])

# Computing eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[4. 2.]

Eigenvectors:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [7]:
import numpy as np

# Data points
x_data = np.array([1, 2, 3, 4, 5])
y_data = np.array([2, 4, 5, 7, 9])

# Performing least squares fitting
A = np.vstack([x_data, np.ones(len(x_data))]).T
m, c = np.linalg.lstsq(A, y_data, rcond=None)[0]

print("Slope (m):", m)
print("Intercept (c):", c)

Slope (m): 1.6999999999999997
Intercept (c): 0.2999999999999996


In [8]:
import numpy as np

# Matrix
A = np.array([[1, 2], [3, 4], [5, 6]])

# Performing SVD
U, s, VT = np.linalg.svd(A, full_matrices=True)

print("U:\n", U)
print("\nSingular Values:\n", s)
print("\nVT:\n", VT)

U:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

Singular Values:
 [9.52551809 0.51430058]

VT:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [9]:
import numpy as np

# Matrix representing a linear transformation
T = np.array([[1, 2], [3, 4]])

# Vector to be transformed
v = np.array([1, 2])

# Applying the linear transformation
transformed_v = np.dot(T, v)

print("Original vector:", v)
print("Transformed vector:", transformed_v)

Original vector: [1 2]
Transformed vector: [ 5 11]


In [10]:
import numpy as np

# Creating an orthogonal matrix
Q = np.array([[1/np.sqrt(2), 1/np.sqrt(2)], [-1/np.sqrt(2), 1/np.sqrt(2)]])

# Vector to be projected
v = np.array([1, 1])

# Projecting the vector onto the column space of Q
projected_v = np.dot(Q, np.dot(Q.T, v))

print("Original vector:", v)
print("Projected vector:", projected_v)

Original vector: [1 1]
Projected vector: [1. 1.]


In [12]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Data
X = np.array([[1], [2], [3], [4], [5]])
y = np.array([2, 4, 5, 7, 9])

# Creating a linear regression model
model = LinearRegression()

# Fitting the model to the data
model.fit(X, y)

# Printing the coefficients
print("Slope (m):", model.coef_[0])
print("Intercept (c):", model.intercept_)

Slope (m): 1.7000000000000002
Intercept (c): 0.2999999999999998


In [13]:
import numpy as np
from sklearn.decomposition import PCA

# Sample data
X = np.array([[2.5, 2.4], [0.5, 0.7], [2.2, 2.9], [1.9, 2.2], [3.1, 3.0], [2.3, 2.7], [2.0, 1.6], [1.0, 1.1], [1.5, 1.6], [1.1, 0.9]])

# Creating a PCA model
pca = PCA(n_components=2)

# Fitting the model to the data
X_transformed = pca.fit_transform(X)

print("Transformed data:")
print(X_transformed)

Transformed data:
[[-0.82797019 -0.17511531]
 [ 1.77758033  0.14285723]
 [-0.99219749  0.38437499]
 [-0.27421042  0.13041721]
 [-1.67580142 -0.20949846]
 [-0.9129491   0.17528244]
 [ 0.09910944 -0.3498247 ]
 [ 1.14457216  0.04641726]
 [ 0.43804614  0.01776463]
 [ 1.22382056 -0.16267529]]
